export const dynamic = 'force-dynamic';
import { env } from '@/lib/env';
import { getSession } from '@/lib/session';
import { GetObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { PrismaClient } from '@prisma/client';
import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

const prisma = new PrismaClient();
const s3 = new S3Client({
  region: env.S3_REGION,
  endpoint: env.S3_ENDPOINT,
  forcePathStyle: true,
  credentials: { accessKeyId: env.S3_ACCESS_KEY, secretAccessKey: env.S3_SECRET_KEY },
});

function parseS3Url(url: string): { bucket: string; key: string; } | null {
  if (!url.startsWith('s3://')) return null;
  const without = url.slice('s3://'.length);
  const slash = without.indexOf('/');
  if (slash <= 0) return null;
  const bucket = without.slice(0, slash);
  const key = without.slice(slash + 1);
  return { bucket, key };
}

export async function GET(req: NextRequest, { params }: { params: { reportId: string; }; }) {
  const session = await getSession();
  if (!session?.email) return NextResponse.json({ ok: false, error: 'Unauthorized' }, { status: 401 });

  const report = await prisma.report.findUnique({
    where: { id: params.reportId },
    include: { attempt: { select: { studentEmail: true, id: true } } },
  });
  if (!report) return NextResponse.json({ ok: false, error: 'Not found' }, { status: 404 });

  // Authorization: student owner or teacher
  const isOwnerStudent = report.attempt?.studentEmail && report.attempt.studentEmail === session.email;
  const isTeacher = session.role === 'TEACHER';
  if (!isOwnerStudent && !isTeacher) {
    return NextResponse.json({ ok: false, error: 'Forbidden' }, { status: 403 });
  }

  // Local filesystem fallback (artifacts generated by worker)
  const attemptId = (report as any).attemptId || report.attempt?.id;
  const type = (report as any).type || 'eleve';
  if (!report.pdfUrl && attemptId) {
    const localDir = '/app/docs/artifacts_premium_final';
    const localName = `${type === 'enseignant' ? 'enseignant' : 'eleve'}_${attemptId}.pdf`;
    const localPath = path.join(localDir, localName);
    if (fs.existsSync(localPath)) {
      const stream = fs.createReadStream(localPath);
      return new Response(stream as unknown as ReadableStream, {
        status: 200,
        headers: {
          'content-type': 'application/pdf',
          'content-disposition': `inline; filename="${localName}"`,
          'cache-control': 'no-store',
        },
      });
    }
    return NextResponse.json({ ok: false, error: 'PDF not available yet' }, { status: 404 });
  }

  // If pdfUrl is S3, stream it; otherwise redirect
  const s3Loc = report.pdfUrl ? parseS3Url(report.pdfUrl) : null;
  if (s3Loc) {
    try {
      const obj = await s3.send(new GetObjectCommand({ Bucket: s3Loc.bucket, Key: s3Loc.key }));
      const body = obj.Body as any; // Readable
      const filename = s3Loc.key.split('/').pop() || 'bilan.pdf';
      return new Response(body as unknown as ReadableStream, {
        status: 200,
        headers: {
          'content-type': 'application/pdf',
          'content-disposition': `inline; filename="${filename}"`,
          'cache-control': 'no-store',
        },
      });
    } catch (e) {
      // S3 failed; attempt local fallback
      const attemptId2 = (report as any).attemptId || report.attempt?.id;
      const type2 = (report as any).type || 'eleve';
      if (attemptId2) {
        const localDir = '/app/docs/artifacts_premium_final';
        const localName = `${type2 === 'enseignant' ? 'enseignant' : 'eleve'}_${attemptId2}.pdf`;
        const localPath = path.join(localDir, localName);
        if (fs.existsSync(localPath)) {
          const stream = fs.createReadStream(localPath);
          return new Response(stream as unknown as ReadableStream, {
            status: 200,
            headers: {
              'content-type': 'application/pdf',
              'content-disposition': `inline; filename="${localName}"`,
              'cache-control': 'no-store',
            },
          });
        }
      }
      return NextResponse.json({ ok: false, error: 'File not found in storage' }, { status: 404 });
    }
  }

  // Fallback: redirect to absolute URL
  if (report.pdfUrl) {
    try {
      return NextResponse.redirect(report.pdfUrl);
    } catch {
      return NextResponse.json({ ok: false, error: 'Invalid pdfUrl' }, { status: 400 });
    }
  }
  return NextResponse.json({ ok: false, error: 'PDF not available yet' }, { status: 404 });
}

// Support HEAD pre-check used by UI before opening the PDF
export async function HEAD(req: NextRequest, { params }: { params: { reportId: string; }; }) {
  const session = await getSession();
  if (!session?.email) return new NextResponse(null, { status: 401 });

  const report = await prisma.report.findUnique({
    where: { id: params.reportId },
    include: { attempt: { select: { studentEmail: true, id: true } } },
  });
  if (!report) return new NextResponse(null, { status: 404 });

  const isOwnerStudent = report.attempt?.studentEmail && report.attempt.studentEmail === session.email;
  const isTeacher = session.role === 'TEACHER';
  if (!isOwnerStudent && !isTeacher) return new NextResponse(null, { status: 403 });

  // Local fallback first
  const attemptId = (report as any).attemptId || report.attempt?.id;
  const type = (report as any).type || 'eleve';
  if (!report.pdfUrl && attemptId) {
    const localDir = '/app/docs/artifacts_premium_final';
    const localName = `${type === 'enseignant' ? 'enseignant' : 'eleve'}_${attemptId}.pdf`;
    const localPath = path.join(localDir, localName);
    if (fs.existsSync(localPath)) return new NextResponse(null, { status: 200 });
    return new NextResponse(null, { status: 404 });
  }

  const s3Loc = report.pdfUrl ? parseS3Url(report.pdfUrl) : null;
  if (s3Loc) {
    try {
      const { HeadObjectCommand } = await import('@aws-sdk/client-s3');
      await s3.send(new HeadObjectCommand({ Bucket: s3Loc.bucket, Key: s3Loc.key } as any));
      return new NextResponse(null, { status: 200 });
    } catch {
      // Try local fallback as a last resort
      const attemptId2 = (report as any).attemptId || report.attempt?.id;
      const type2 = (report as any).type || 'eleve';
      if (attemptId2) {
        const localDir = '/app/docs/artifacts_premium_final';
        const localName = `${type2 === 'enseignant' ? 'enseignant' : 'eleve'}_${attemptId2}.pdf`;
        const localPath = path.join(localDir, localName);
        if (fs.existsSync(localPath)) return new NextResponse(null, { status: 200 });
      }
      return new NextResponse(null, { status: 404 });
    }
  }
  // Non-S3 URL: we assume reachable; the GET will redirect. Return 200.
  return new NextResponse(null, { status: 200 });
}

